apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pause
  name: pause
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      containers:
      - image: k8s.gcr.io/pause
        name: pause
        securityContext:
          privileged: true