apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp:restricted:serviceaccounts
roleRef:
  kind: ClusterRole
  name: psp:vmware-system-restricted
  apiGroup: rbac.authorization.k8s.io
subjects:
# Authorize all service accounts in cluster
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: system:serviceaccounts